Updated gitignore file
albinJoseph1/luigis pull request #4
Opened 2024-01-04 09:27 UTC by albinJoseph1

Removed core files from gitginore and pushed the core files separately

2024-01-04 10:56 UTC, Haznasait requested changes

2024-01-04 10:56 UTC, Haznasait commented on .gitignore
> +
Remove the unwanted line

2024-01-04 11:51 UTC, Haznasait requested changes

2024-01-04 11:51 UTC, Haznasait commented on .gitignore
> -#/wp-content/themes
Remove the unwanted changes

2024-01-05 05:40 UTC, Haznasait approved these changes

2024-01-05 10:58 UTC, albinJoseph1 commented on wp-admin/about.php
nope, is there any issue?

2024-01-09 04:54 UTC, Haznasait approved these changes

2024-01-09 06:16 UTC, AbhijithHaridas approved these changes

2024-01-09 06:16 UTC, merged